### ISSUE TITLE
[Run configurations... dialog] Opening a JUnit configuration takes too long (UI freeze)

### ISSUE THREAD

**Issue by fedejeanne** [vi-eclipse/Eclipse-JDT#8]
This issue is a specific use case of https://github.com/vi-eclipse/Eclipse-Platform/issues/3. Check that issue for more details and expected behavior.

**Comment by fedejeanne** [comment]
Transferred to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/683

**Comment by HeikoKlare** [comment]
@fedejeanne This issue is "open" but has been moved to "Done" in our backlog. Can you please either move it to the proper state in the backlog or document how/why it is done and close it afterwards?

**Comment by fedejeanne** [comment]
This issue was fixed by https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/675: a progress indicator was added

**Comment by HeikoKlare** [comment]
Do we already have some follow-up issue for improving the handling of the long running action (making it faster, performing it asynchronously, performing it on-demand etc,)? Otherwise we should create that one.

**Comment by fedejeanne** [comment]
There's https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1214 . Is that what you mean?

I haven't spent any time on that though. I could start looking into it next week if you want? It will probably overlap with other performance issues in JDT so it would make sense to go over it together.

**Comment by HeikoKlare** [comment]
That is one option. But we also discussed alternatives/additions like computing the super types asynchronously and disabling the according field in the UI as long as it has not been calculated. Or even to compute whole launch configuration pages asynchronously and show a progress bar in the right side of the launch configurations dialog while loading the information. Those approaches would ensure that even in case of regressions w.r.t. single data providers for the dialog, it will still stay responsibe (i.e., it will avoid performance regressions such as the existing ones).

I'd like to have an issue or multiple issues documenting those ideas in our backlog. I would also like to have an issue in our backlog representing https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1214. Otherwise we won't know that there is some JDT issue of that specific interest for us.

**Comment by HeikoKlare** [comment]
I see that we also have https://github.com/vi-eclipse/Eclipse-Platform/issues/3, so it might make sense to document those ideas there and only have a separate JDT-specific backlog item for which the jdt.core issue already exists.

**Comment by fedejeanne** [comment]
See https://github.com/vi-eclipse/Eclipse-JDT/issues/16
